import json
import shutil
from pathlib import Path
from typing import Any
from uuid import UUID

from app.core.constants import DOCUMENTS_DIR


class StorageService:
    """
    Handles all filesystem operations related to document storage.
    """

    def create_workspace(
        self,
        document_id: UUID,
    ) -> Path:
        """
        Create the complete workspace directory structure
        for a document.
        """

        workspace = DOCUMENTS_DIR / str(document_id)

        directories = [
            workspace,
            workspace / "original",
            workspace / "parsed",
            workspace / "chunks",
            workspace / "embeddings",
            workspace / "exports",
        ]

        for directory in directories:
            directory.mkdir(
                parents=True,
                exist_ok=True,
            )

        return workspace

    def get_workspace(
        self,
        document_id: UUID,
    ) -> Path:
        """
        Returns the workspace path of a document.
        """

        return DOCUMENTS_DIR / str(document_id)

    def save_original_file(
        self,
        source: Path,
        workspace: Path,
    ) -> Path:
        """
        Save the uploaded document inside its workspace.
        """

        destination = (
            workspace
            / "original"
            / "original.pdf"
        )

        shutil.copy2(
            source,
            destination,
        )

        return destination

    def save_json(
        self,
        data: dict | list | Any,
        destination: Path,
    ) -> None:
        """
        Generic helper to save JSON data.
        """

        with destination.open(
            "w",
            encoding="utf-8",
        ) as file:
            json.dump(
                data,
                file,
                indent=4,
                ensure_ascii=False,
            )

    def save_metadata(
        self,
        metadata,
        workspace: Path,
    ) -> Path:
        """
        Save document metadata.
        """

        metadata_path = workspace / "metadata.json"

        self.save_json(
            metadata.model_dump(mode="json"),
            metadata_path,
        )

        return metadata_path

    def save_manifest(
        self,
        manifest,
        workspace: Path,
    ) -> Path:
        """
        Save document processing manifest.
        """

        manifest_path = workspace / "manifest.json"

        self.save_json(
            manifest.model_dump(mode="json"),
            manifest_path,
        )

        return manifest_path

    def update_manifest(
        self,
        manifest,
        workspace: Path,
    ) -> None:
        """
        Update the manifest file.
        """

        self.save_manifest(
            manifest,
            workspace,
        )

    def save_markdown(
        self,
        markdown: str,
        workspace: Path,
    ) -> Path:
        """
        Save parsed markdown generated by Docling.
        """

        markdown_path = (
            workspace
            / "parsed"
            / "parsed.md"
        )

        with markdown_path.open(
            "w",
            encoding="utf-8",
        ) as file:
            file.write(markdown)

        return markdown_path

    def save_chunks(
        self,
        chunks: list[dict],
        workspace: Path,
    ) -> Path:
        """
        Save semantic chunks.
        """

        chunks_path = (
            workspace
            / "chunks"
            / "chunks.json"
        )

        self.save_json(
            chunks,
            chunks_path,
        )

        return chunks_path

    # ------------------------------------------------------------------
    # Workspace Helper Methods
    # ------------------------------------------------------------------

    def get_original_document(
        self,
        workspace: Path,
    ) -> Path:
        """
        Returns the original uploaded document.
        """

        return (
            workspace
            / "original"
            / "original.pdf"
        )

    def get_parsed_markdown(
        self,
        workspace: Path,
    ) -> Path:
        """
        Returns the parsed markdown file.
        """

        return (
            workspace
            / "parsed"
            / "parsed.md"
        )

    def get_chunks_path(
        self,
        workspace: Path,
    ) -> Path:
        """
        Returns the chunks.json file path.
        """

        return (
            workspace
            / "chunks"
            / "chunks.json"
        )

    def get_embeddings_directory(
        self,
        workspace: Path,
    ) -> Path:
        """
        Returns the embeddings directory.
        """

        return (
            workspace
            / "embeddings"
        )

    def get_exports_directory(
        self,
        workspace: Path,
    ) -> Path:
        """
        Returns the exports directory.
        """

        return (
            workspace
            / "exports"
        )
    
    def save_chunk_graph(
        self,
        graph: dict,
        workspace: Path,
    ) -> Path:
        """
        Save chunk graph.
        """

        graph_path = (
            workspace
            / "chunks"
            / "graph.json"
        )

        self.save_json(
            graph,
            graph_path,
        )

        return graph_path
    
    def get_chunk_graph_path(
        self,
        workspace: Path,
    ) -> Path:
        """
        Returns the chunk graph file path.
        """

        return (
            workspace
            / "chunks"
            / "graph.json"
        )
    
    def save_embeddings(
        self,
        embeddings: list[list[float]],
        workspace: Path,
    ) -> Path:
        """
        Save generated embeddings.
        """

        embedding_path = (
            workspace
            / "embeddings"
            / "embeddings.json"
        )

        self.save_json(
            embeddings,
            embedding_path,
        )

        return embedding_path